// Registration tokens generated by HR and emailed to prospective employees.
// Valid for REGISTRATION_TOKEN_TTL_HOURS (default 3h).

const mongoose = require('mongoose');

const registrationTokenSchema = new mongoose.Schema(
  {
    // email: { type: String, required: true, lowercase: true },
    // name: String,
    // token: { type: String, required: true, unique: true },
    // expiresAt: { type: Date, required: true },
    // used: { type: Boolean, default: false },
    // // linked once the new employee submits their onboarding application
    // user: { type: mongoose.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);

module.exports = mongoose.model('RegistrationToken', registrationTokenSchema);
